# Generated by Django 5.2.3 on 2025-06-18 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        default=2025,
                        max_length=4,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code='invalid_year',
                                message='O ano deve conter exatamente 4 dígitos numéricos.',
                                regex='^\\d{4}$',
                            )
                        ],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
