name: CI/Blog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/*

env:
  ROOT_PATH: django_blog/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Cd
        run: cd ${{ env.ROOT_PATH }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Environment
        run: |
          mv .env.example .env

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt 

      - name: Formater
        run: make fmt

      - name: Linter
        run: echo "todo"

      - name: System Checks
        run: |
          python manage.py check # Roda as checagens básicas do Django

    #   - name: Run Django Migrations (Dry Run)
    #     # É uma boa prática fazer um dry run das migrações para garantir que não há problemas
    #     run: |
    #       python manage.py migrate --check --noinput
    #     continue-on-error: true # Permite que o workflow continue mesmo se houver erro aqui

    #   - name: Run Tests
    #     # Adapte este comando para como você roda seus testes Django
    #     run: |
    #       python manage.py test # Roda os testes do seu projeto Django